/**
 * รายจ่าย — typing money out (Step 8).
 *
 * The only screen in the system where a person enters money with no bill, no
 * customer and no kitchen ticket behind it, so two things drive the design:
 *
 *  - IT HAS TO BE FASTER THAN THE NOTEBOOK IT REPLACES. Category is six big
 *    buttons, not a dropdown; the date starts on today; the amount is the only
 *    field that must be typed, and it is focused on open. Anything slower than
 *    writing "ของสด 800" on paper simply will not get used, and an expense
 *    that never gets entered makes every P&L below it wrong.
 *  - NOTHING IS DELETED QUIETLY. Removing a row asks first, and the server
 *    writes an audit entry either way (rule #8).
 *
 * Rows created by a payroll run (Step 9) come back with `isAutoGenerated` and
 * are shown without edit buttons — the payslip is the record, and a
 * hand-edited copy of it would make the two disagree.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  EXPENSE_CATEGORIES,
  ExpenseCategory,
  expenseCategoryLabel,
  formatSatang,
  parseBahtToSatang,
  Permission,
  satangToBaht,
  yearMonthOf,
  type ExpenseDto,
  type ExpenseListResponse,
  type ExpenseRequest,
} from '@pos/shared';
import { officeApi } from '../../api-office.js';
import { useBusinessToday } from '../../business-day.js';
import { Card, ReportShell, Row } from '../../components/office/ReportShell.js';
import { useSession } from '../../session.js';

interface Draft {
  date: string;
  category: ExpenseCategory;
  amount: string;
  note: string;
}

export function ExpensesPage(): React.ReactElement {
  const today = useBusinessToday();
  const canWrite = useSession((state) => state.can(Permission.MANAGE_EXPENSE));

  const [month, setMonth] = useState(() => yearMonthOf(today));
  const [data, setData] = useState<ExpenseListResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState<Draft>(() => emptyDraft(today));
  const amountRef = useRef<HTMLInputElement>(null);

  const load = useCallback(async (on: string) => {
    setLoading(true);
    const result = await officeApi.expenses(on);
    setLoading(false);
    if (result.ok) {
      setData(result.data);
      setError(null);
    } else {
      setError(result.offline ? 'ต่อเซิร์ฟเวอร์ไม่ได้ — หน้านี้ต้องออนไลน์' : result.error);
    }
  }, []);

  useEffect(() => {
    void load(month);
  }, [month, load]);

  const submit = useCallback(async () => {
    const amountSatang = parseBahtToSatang(draft.amount);
    if (amountSatang === null || amountSatang <= 0) {
      setError('ใส่จำนวนเงินให้ถูกต้อง');
      return;
    }
    const input: ExpenseRequest = {
      date: draft.date,
      category: draft.category,
      amountSatang,
      note: draft.note.trim() === '' ? null : draft.note.trim(),
      paidBy: 'CASH',
    };

    setBusy(true);
    const result = editingId
      ? await officeApi.updateExpense(editingId, input)
      : await officeApi.createExpense(input);
    setBusy(false);

    if (!result.ok) {
      setError(result.offline ? 'ต่อเซิร์ฟเวอร์ไม่ได้ — บันทึกไม่สำเร็จ' : result.error);
      return;
    }
    setError(null);
    setData(result.data);
    // The response is the month the row now lives in, which may not be the
    // month on screen if the date was changed. Follow it rather than reload
    // the month the row just left.
    setMonth(result.data.yearMonth);
    setEditingId(null);
    // Keep the date and category: entering a day's receipts means typing five
    // ของสด rows in a row, and resetting both every time is five extra taps.
    setDraft((current) => ({ ...current, amount: '', note: '' }));
    amountRef.current?.focus();
  }, [draft, editingId]);

  const remove = useCallback(async (expense: ExpenseDto) => {
    if (!globalThis.confirm(`ลบรายจ่าย ${formatSatang(expense.amountSatang)} นี้?`)) return;
    setBusy(true);
    const result = await officeApi.deleteExpense(expense.id);
    setBusy(false);
    if (result.ok) {
      setData(result.data);
      setError(null);
    } else {
      setError(result.error);
    }
  }, []);

  const startEdit = useCallback((expense: ExpenseDto) => {
    setEditingId(expense.id);
    setDraft({
      date: expense.date,
      category: (expense.category as ExpenseCategory) ?? ExpenseCategory.OTHER,
      amount: String(satangToBaht(expense.amountSatang)),
      note: expense.note ?? '',
    });
  }, []);

  const byCategory = useMemo(() => data?.byCategory ?? [], [data]);

  const controls = (
    <label className="flex items-center gap-2">
      <span className="text-sm text-slate-600">เดือน</span>
      <input
        type="month"
        aria-label="เดือน"
        value={month}
        onChange={(event) => setMonth(event.target.value)}
        className="tnum h-12 rounded-xl border border-slate-300 px-3 text-lg"
      />
    </label>
  );

  return (
    <ReportShell controls={controls} error={error} loading={loading && data === null}>
      <div className="grid gap-4 lg:grid-cols-[2fr_1fr]">
        <div className="space-y-4">
          {canWrite ? (
            <form
              aria-label={editingId ? 'แก้ไขรายจ่าย' : 'บันทึกรายจ่าย'}
              onSubmit={(event) => {
                event.preventDefault();
                void submit();
              }}
              className="rounded-2xl bg-white p-5"
            >
              <h2 className="text-lg font-semibold">
                {editingId ? 'แก้ไขรายจ่าย' : 'บันทึกรายจ่าย'}
              </h2>

              <div className="mt-3 grid grid-cols-3 gap-2">
                {EXPENSE_CATEGORIES.map((category) => (
                  <button
                    key={category.key}
                    type="button"
                    aria-pressed={draft.category === category.key}
                    onClick={() => setDraft((current) => ({ ...current, category: category.key }))}
                    className={`btn h-16 flex-col gap-0 px-2 ${
                      draft.category === category.key
                        ? 'bg-brand-600 text-white'
                        : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                    }`}
                  >
                    <span className="font-semibold">{category.label}</span>
                    <span className="text-xs opacity-70">{category.hint}</span>
                  </button>
                ))}
              </div>

              <div className="mt-3 flex flex-wrap items-end gap-3">
                <label className="w-44">
                  <span className="text-sm text-slate-600">วันที่</span>
                  <input
                    type="date"
                    aria-label="วันที่"
                    value={draft.date}
                    onChange={(event) =>
                      setDraft((current) => ({ ...current, date: event.target.value }))
                    }
                    className="tnum mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 text-lg"
                  />
                </label>
                <label className="w-40">
                  <span className="text-sm text-slate-600">จำนวนเงิน (บาท)</span>
                  <input
                    ref={amountRef}
                    type="text"
                    inputMode="decimal"
                    aria-label="จำนวนเงิน (บาท)"
                    value={draft.amount}
                    onChange={(event) =>
                      setDraft((current) => ({ ...current, amount: event.target.value }))
                    }
                    className="tnum mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 text-right text-lg"
                  />
                </label>
                <label className="min-w-48 flex-1">
                  <span className="text-sm text-slate-600">หมายเหตุ</span>
                  <input
                    type="text"
                    aria-label="หมายเหตุ"
                    value={draft.note}
                    placeholder="เช่น หมูสด 5 กก. เจ๊แดง"
                    onChange={(event) =>
                      setDraft((current) => ({ ...current, note: event.target.value }))
                    }
                    className="mt-1 h-12 w-full rounded-xl border border-slate-300 px-3 text-lg"
                  />
                </label>
                <button
                  type="submit"
                  disabled={busy}
                  className="btn h-12 bg-brand-600 px-8 text-white hover:bg-brand-500 disabled:opacity-50"
                >
                  {editingId ? 'บันทึกการแก้ไข' : 'บันทึก'}
                </button>
                {editingId ? (
                  <button
                    type="button"
                    onClick={() => {
                      setEditingId(null);
                      setDraft(emptyDraft(today));
                    }}
                    className="btn h-12 bg-slate-100 px-6 text-slate-700 hover:bg-slate-200"
                  >
                    ยกเลิก
                  </button>
                ) : null}
              </div>
            </form>
          ) : null}

          <ul className="space-y-2">
            {(data?.expenses ?? []).map((expense) => (
              <li
                key={expense.id}
                className="flex flex-wrap items-center gap-3 rounded-2xl bg-white p-4"
              >
                <span className="tnum w-28 text-slate-500">{expense.date}</span>
                <span className="w-28 font-medium">{expenseCategoryLabel(expense.category)}</span>
                <span className="min-w-40 flex-1 text-slate-600">{expense.note ?? ''}</span>
                <span className="tnum w-28 text-right text-lg font-semibold">
                  {formatSatang(expense.amountSatang)}
                </span>
                {canWrite && !expense.isAutoGenerated ? (
                  <>
                    <button
                      type="button"
                      onClick={() => startEdit(expense)}
                      className="btn h-11 bg-slate-100 px-4 text-slate-700 hover:bg-slate-200"
                    >
                      แก้ไข
                    </button>
                    <button
                      type="button"
                      onClick={() => void remove(expense)}
                      disabled={busy}
                      className="btn h-11 bg-red-50 px-4 text-red-800 hover:bg-red-100 disabled:opacity-50"
                    >
                      ลบ
                    </button>
                  </>
                ) : expense.isAutoGenerated ? (
                  // Only when a payroll run wrote it. Saying this on every row
                  // to a role that merely cannot edit would be a lie about
                  // where the money came from.
                  <span className="text-sm text-slate-400">มาจากการจ่ายเงินเดือน</span>
                ) : null}
              </li>
            ))}
            {data && data.expenses.length === 0 ? (
              <li className="rounded-2xl bg-white p-6 text-center text-slate-400">
                ยังไม่มีรายจ่ายในเดือนนี้
              </li>
            ) : null}
          </ul>
        </div>

        <Card title="รวมทั้งเดือน">
          {byCategory.map((row) => (
            <Row
              key={row.category}
              label={expenseCategoryLabel(row.category)}
              value={formatSatang(row.amountSatang)}
            />
          ))}
          <Row label="รวม" value={formatSatang(data?.totalSatang ?? 0)} strong />
        </Card>
      </div>
    </ReportShell>
  );
}

function emptyDraft(today: string): Draft {
  return { date: today, category: ExpenseCategory.INGREDIENT, amount: '', note: '' };
}
