/**
 * Typing money out.
 *
 * The thing that decides whether this feature works is not correctness, it is
 * speed: entering a day's receipts means five ของสด rows in a row, and if each
 * one costs re-picking the category and re-typing the date, the notebook wins
 * and every P&L built on this table is wrong.
 *
 * So the two tests that matter are that the form KEEPS the category and the
 * date after a save, and that the screen follows a row that was moved into
 * another month instead of quietly losing it.
 */

import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { MemoryRouter } from 'react-router-dom';
import { toBusinessDate, type ExpenseListResponse } from '@pos/shared';
import { api } from '../../api-client.js';
import { ExpensesPage } from './ExpensesPage.js';

/** Computed the same way the screen does, so this asserts "today in the
 *  branch's terms" rather than freezing the clock around the whole file. */
const TODAY = toBusinessDate(new Date(), { timezone: 'Asia/Bangkok', dayCutoffHour: 4 });

vi.mock('../../api-client.js', () => ({
  api: {
    expenses: vi.fn(),
    createExpense: vi.fn(),
    updateExpense: vi.fn(),
    deleteExpense: vi.fn(),
  },
}));

let allowed = true;
vi.mock('../../session.js', () => ({
  useSession: (selector: (state: unknown) => unknown) =>
    selector({
      branch: { timezone: 'Asia/Bangkok', dayCutoffHour: 4 },
      can: () => allowed,
    }),
}));

function list(overrides: Partial<ExpenseListResponse> = {}): ExpenseListResponse {
  return {
    yearMonth: '2026-07',
    expenses: [
      {
        id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        date: '2026-07-30',
        category: 'INGREDIENT',
        amountSatang: 80_000,
        note: 'หมูสด 5 กก.',
        paidBy: 'CASH',
        isAutoGenerated: false,
        createdAt: '2026-07-30T10:00:00.000Z',
      },
    ],
    totalSatang: 80_000,
    byCategory: [{ category: 'INGREDIENT', amountSatang: 80_000 }],
    ...overrides,
  };
}

async function show(data: ExpenseListResponse = list()): Promise<void> {
  vi.mocked(api.expenses).mockResolvedValue({ ok: true, data });
  render(
    <MemoryRouter>
      <ExpensesPage />
    </MemoryRouter>,
  );
  await waitFor(() => expect(screen.getByText('หมูสด 5 กก.')).toBeInTheDocument());
}

/**
 * Sets a controlled field.
 *
 * fireEvent.change rather than userEvent.type: every field here is controlled
 * by React state, and typing character by character into one only re-tests
 * React. It also keeps `clear()` out of the way, which fights with the
 * date/month inputs.
 */
async function type(label: string, value: string): Promise<void> {
  await act(async () => {
    fireEvent.change(screen.getByLabelText(label), { target: { value } });
  });
}

async function tap(element: HTMLElement): Promise<void> {
  await act(async () => {
    await userEvent.setup().click(element);
  });
}

beforeEach(() => {
  vi.clearAllMocks();
  allowed = true;
});

describe('entering a receipt', () => {
  it('opens on today with วัตถุดิบ already picked', async () => {
    // The two answers that are right nine times out of ten. Anything that has
    // to be chosen every time is a tap this screen cannot afford.
    await show();
    expect(screen.getByLabelText('วันที่')).toHaveValue(TODAY);
    expect(screen.getByRole('button', { name: /วัตถุดิบ/ })).toHaveAttribute(
      'aria-pressed',
      'true',
    );
  });

  it('sends satang, not baht', async () => {
    vi.mocked(api.createExpense).mockResolvedValue({ ok: true, data: list() });
    await show();

    await type('จำนวนเงิน (บาท)', '800.50');
    await tap(screen.getByRole('button', { name: 'บันทึก' }));

    expect(api.createExpense).toHaveBeenCalledWith(
      expect.objectContaining({ amountSatang: 80_050, category: 'INGREDIENT' }),
    );
  });

  it('keeps the category and the date for the next row', async () => {
    vi.mocked(api.createExpense).mockResolvedValue({ ok: true, data: list() });
    await show();

    await tap(screen.getByRole('button', { name: /ค่าแรง/ }));
    await type('จำนวนเงิน (บาท)', '300');
    await tap(screen.getByRole('button', { name: 'บันทึก' }));

    // Amount cleared so the next figure can be typed straight in; category and
    // date left alone because the next receipt is almost always the same kind
    // from the same day.
    expect(screen.getByLabelText('จำนวนเงิน (บาท)')).toHaveValue('');
    expect(screen.getByLabelText('วันที่')).toHaveValue(TODAY);
    expect(screen.getByRole('button', { name: /ค่าแรง/ })).toHaveAttribute('aria-pressed', 'true');
  });

  it('refuses a figure that is not a number instead of sending it', async () => {
    await show();
    await type('จำนวนเงิน (บาท)', 'แปดร้อย');
    await tap(screen.getByRole('button', { name: 'บันทึก' }));

    expect(api.createExpense).not.toHaveBeenCalled();
    expect(screen.getByRole('alert')).toHaveTextContent('ใส่จำนวนเงินให้ถูกต้อง');
  });

  it('follows a row moved into another month rather than losing it', async () => {
    vi.mocked(api.updateExpense).mockResolvedValue({
      ok: true,
      data: list({ yearMonth: '2026-08', expenses: [], totalSatang: 0, byCategory: [] }),
    });
    await show();

    await tap(screen.getByRole('button', { name: 'แก้ไข' }));
    await type('วันที่', '2026-08-02');
    await tap(screen.getByRole('button', { name: 'บันทึกการแก้ไข' }));

    // The server answers with the month the row now lives in; reloading the
    // month it left would show the user their expense disappearing.
    expect(screen.getByLabelText('เดือน')).toHaveValue('2026-08');
  });
});

describe('rows a payroll run created', () => {
  it('cannot be edited from here', async () => {
    await show(
      list({
        expenses: [{ ...list().expenses[0]!, isAutoGenerated: true, category: 'WAGE' }],
      }),
    );
    expect(screen.queryByRole('button', { name: 'แก้ไข' })).not.toBeInTheDocument();
    expect(screen.getByText('มาจากการจ่ายเงินเดือน')).toBeInTheDocument();
  });
});

describe('a role that may read but not write', () => {
  it('hides the form entirely rather than showing buttons that will 403', async () => {
    allowed = false;
    await show();
    expect(screen.queryByLabelText('จำนวนเงิน (บาท)')).not.toBeInTheDocument();
    // The row is still readable, and it must NOT be labelled as coming from a
    // payroll run just because this role cannot edit it.
    expect(screen.getAllByText('800.00').length).toBeGreaterThan(0);
    expect(screen.queryByText('มาจากการจ่ายเงินเดือน')).not.toBeInTheDocument();
  });
});
