/**
 * Moving a bill between tables, merging two bills, splitting one in two.
 *
 * These are the three things a cashier does when the seating plan and the
 * paperwork stop agreeing, and all three are BILL EDITS — rule #8 names them
 * in the same breath as voids and discounts, so every one of them writes an
 * audit row saying who did it and what it looked like before.
 *
 * The unifying rule, and the reason this file exists rather than three
 * scattered checks: NOTHING HERE MAY CHANGE WHAT ANYTHING COSTS. A line keeps
 * the price and cost snapshotted when it was rung up (rule #7) and keeps its
 * own id (rule #6); moving it to another bill moves the row, it does not
 * re-price it. If any operation in here could make a customer pay a different
 * total than the sum of what they ordered, it is wrong.
 *
 * WHAT IS DELIBERATELY REFUSED, and why refusing beats guessing:
 *
 *   - splitting off EVERY line — that leaves an empty bill behind and is a
 *     table move wearing a costume; the shop meant one of the other two.
 *   - splitting or merging a line that has been VOIDED — a void is evidence of
 *     something that happened on THAT bill (rule #8). Moving it would move the
 *     evidence away from the event.
 *   - merging bills from different trading days — rule #4 puts a bill on the
 *     day it belongs to, and merging across the 04:00 cutoff would move
 *     yesterday's sales into today's takings.
 *   - merging when either bill carries a discount — see canMergeBills.
 */

import { z } from 'zod';
import type { OrderLineDto } from './order.js';
import { uuidSchema } from './schemas.js';

/* ------------------------------------------------------------------ */
/* requests                                                            */
/* ------------------------------------------------------------------ */

/**
 * ย้ายโต๊ะ — the same bill, a different table.
 *
 * Table to table only. "Move this dine-in bill to no table at all" would turn
 * it into a takeaway bill, which is a channel change and a different thing:
 * the customer is still sitting there.
 */
export const moveTableRequestSchema = z.object({ tableId: uuidSchema });
export type MoveTableRequest = z.infer<typeof moveTableRequestSchema>;

/**
 * รวมบิล — everything on `fromOrderId` moves onto the bill in the URL, and the
 * emptied bill is cancelled.
 *
 * The direction is stated rather than inferred. "Merge A and B" has to answer
 * "which number survives", and the surviving bill is the one the cashier is
 * looking at.
 */
export const mergeBillsRequestSchema = z.object({ fromOrderId: uuidSchema });
export type MergeBillsRequest = z.infer<typeof mergeBillsRequestSchema>;

/**
 * แยกบิล — the chosen lines move to a NEW bill.
 *
 * `newOrderId` is generated by the tablet (rule #6), so a retried request
 * lands on the same bill instead of splitting twice.
 *
 * The new bill stays at the SAME TABLE. That is the whole point: four people
 * at one table paying separately are four bills at one table, which is what
 * TableSession has always modelled.
 */
export const splitBillRequestSchema = z.object({
  newOrderId: uuidSchema,
  lineIds: z.array(uuidSchema).min(1, 'เลือกรายการที่จะแยกอย่างน้อย 1 รายการ').max(200),
});
export type SplitBillRequest = z.infer<typeof splitBillRequestSchema>;

/* ------------------------------------------------------------------ */
/* what may be split                                                   */
/* ------------------------------------------------------------------ */

export type SplitRefusal =
  | 'NOTHING_SELECTED'
  | 'LINE_NOT_ON_BILL'
  | 'LINE_VOIDED'
  | 'LINE_AWAITING_APPROVAL'
  | 'DUPLICATE_LINE'
  | 'WOULD_EMPTY_BILL'
  | 'DISCOUNTED';

/** The little a split needs to know about the bill it is cutting up. */
export interface SplittableBill {
  discountSatang: number;
  lines: readonly OrderLineDto[];
}

export interface SplitPlan {
  /** Lines that move to the new bill. */
  moving: OrderLineDto[];
  /** Lines that stay on the original. Never empty — see WOULD_EMPTY_BILL. */
  staying: OrderLineDto[];
}

export type SplitCheck =
  { ok: true; plan: SplitPlan } | { ok: false; refusal: SplitRefusal; message: string };

/** A line that counts towards the bill: not voided, not a QR request in limbo. */
function isLive(line: OrderLineDto): boolean {
  return line.voidedAt === null && !(line.source === 'QR' && line.approvedAt === null);
}

/**
 * Works out which lines go and which stay, or says why it will not.
 *
 * Runs on BOTH sides: the dialog uses it to grey out the button with the same
 * message the server would send back, so the cashier learns the rule before
 * committing rather than after. The server runs it again because a client's
 * opinion about what is on a bill is not evidence.
 */
export function planSplit(bill: SplittableBill, lineIds: readonly string[]): SplitCheck {
  const { lines } = bill;

  if (bill.discountSatang > 0) {
    // Same argument as canMergeBills: the amount was agreed against THIS bill,
    // and after the cut there are two. Splitting it in half invents a figure
    // nobody approved; leaving it whole on one side makes the other customer
    // pay a discount they were promised a share of.
    return {
      ok: false,
      refusal: 'DISCOUNTED',
      message: 'บิลที่มีส่วนลดแยกไม่ได้ — ยกเลิกส่วนลดก่อน แล้วค่อยลดใหม่บนบิลที่แยกแล้ว',
    };
  }

  if (lineIds.length === 0) {
    return { ok: false, refusal: 'NOTHING_SELECTED', message: 'ยังไม่ได้เลือกรายการที่จะแยก' };
  }

  const wanted = new Set(lineIds);
  if (wanted.size !== lineIds.length) {
    return { ok: false, refusal: 'DUPLICATE_LINE', message: 'มีรายการซ้ำในรายการที่เลือก' };
  }

  const byId = new Map(lines.map((line) => [line.id, line]));
  for (const id of lineIds) {
    const line = byId.get(id);
    if (!line) {
      return { ok: false, refusal: 'LINE_NOT_ON_BILL', message: 'มีรายการที่ไม่ได้อยู่ในบิลนี้' };
    }
    if (line.voidedAt !== null) {
      // The void is a record of something that happened on this bill.
      return {
        ok: false,
        refusal: 'LINE_VOIDED',
        message: `"${line.nameSnapshot}" ถูกยกเลิกไปแล้ว แยกไปบิลใหม่ไม่ได้`,
      };
    }
    if (line.source === 'QR' && line.approvedAt === null) {
      return {
        ok: false,
        refusal: 'LINE_AWAITING_APPROVAL',
        message: `"${line.nameSnapshot}" ยังรออนุมัติ — กดอนุมัติหรือปฏิเสธก่อน`,
      };
    }
  }

  const live = lines.filter(isLive);
  const staying = live.filter((line) => !wanted.has(line.id));
  if (staying.length === 0) {
    return {
      ok: false,
      refusal: 'WOULD_EMPTY_BILL',
      message: 'แยกทุกรายการออกไม่ได้ — บิลเดิมจะว่าง ถ้าต้องการย้ายทั้งบิลให้ใช้ "ย้ายโต๊ะ"',
    };
  }

  return {
    ok: true,
    plan: { moving: live.filter((line) => wanted.has(line.id)), staying },
  };
}

/* ------------------------------------------------------------------ */
/* what may be merged                                                  */
/* ------------------------------------------------------------------ */

export type MergeRefusal =
  'SAME_BILL' | 'NOT_OPEN' | 'DIFFERENT_DAY' | 'DISCOUNTED' | 'NOTHING_TO_MOVE';

/** The little a merge needs to know about each side. */
export interface MergeCandidate {
  id: string;
  status: string;
  businessDate: string;
  discountSatang: number;
  lines: readonly OrderLineDto[];
}

export type MergeCheck = { ok: true } | { ok: false; refusal: MergeRefusal; message: string };

/**
 * Whether `source` may be poured into `target`.
 *
 * THE DISCOUNT RULE IS THE ONE WORTH ARGUING ABOUT. A discount is an amount a
 * supervisor agreed against ONE bill (see discount.ts) — ฿20 off a ฿100 bill.
 * After a merge that bill does not exist any more, so neither reading is
 * honest: carrying the amount over applies a figure agreed for one total to a
 * different total, and dropping it silently charges the customer ฿20 they were
 * promised they would not pay.
 *
 * So neither. Clear the discount, merge, and let a supervisor put a discount on
 * the bill that now exists. It costs ten seconds and leaves one audit trail
 * that says what was actually agreed, instead of two that describe bills nobody
 * can point at.
 */
export function canMergeBills(target: MergeCandidate, source: MergeCandidate): MergeCheck {
  if (target.id === source.id) {
    return { ok: false, refusal: 'SAME_BILL', message: 'รวมบิลกับตัวเองไม่ได้' };
  }
  if (target.status !== 'OPEN' || source.status !== 'OPEN') {
    return { ok: false, refusal: 'NOT_OPEN', message: 'รวมได้เฉพาะบิลที่ยังเปิดอยู่' };
  }
  if (target.businessDate !== source.businessDate) {
    // Rule #4. Merging across the cutoff would move yesterday's sales into
    // today's takings, and both days' reports would then be wrong.
    return {
      ok: false,
      refusal: 'DIFFERENT_DAY',
      message: 'สองบิลนี้อยู่คนละวันขาย รวมกันไม่ได้',
    };
  }
  if (target.discountSatang > 0 || source.discountSatang > 0) {
    return {
      ok: false,
      refusal: 'DISCOUNTED',
      message: 'บิลที่มีส่วนลดรวมไม่ได้ — ยกเลิกส่วนลดก่อน แล้วค่อยลดใหม่บนบิลที่รวมแล้ว',
    };
  }
  if (source.lines.filter(isLive).length === 0) {
    return {
      ok: false,
      refusal: 'NOTHING_TO_MOVE',
      message: 'บิลที่จะรวมเข้ามาไม่มีรายการ — ยกเลิกบิลนั้นแทน',
    };
  }
  return { ok: true };
}

/* ------------------------------------------------------------------ */
/* what the audit log reads like                                       */
/* ------------------------------------------------------------------ */

export const BILL_MOVE_ACTIONS = {
  MOVE_TABLE: 'ORDER_MOVE_TABLE',
  MERGE: 'ORDER_MERGE',
  SPLIT: 'ORDER_SPLIT',
} as const;

/** "ย้ายจากโต๊ะ A1 ไปโต๊ะ B2" — readable a month later without joining anything. */
export function describeTableMove(fromTable: string | null, toTable: string): string {
  return fromTable ? `ย้ายจากโต๊ะ ${fromTable} ไปโต๊ะ ${toTable}` : `ย้ายไปโต๊ะ ${toTable}`;
}

/** "รวมบิล 260730-002 (3 รายการ) เข้ากับ 260730-001" */
export function describeMerge(sourceLabel: string, targetLabel: string, lineCount: number): string {
  return `รวมบิล ${sourceLabel} (${lineCount} รายการ) เข้ากับ ${targetLabel}`;
}

/** "แยก 2 รายการออกจากบิล 260730-001 ไปบิลใหม่" */
export function describeSplit(sourceLabel: string, lineCount: number): string {
  return `แยก ${lineCount} รายการออกจากบิล ${sourceLabel} ไปบิลใหม่`;
}
