/**
 * People, what they are owed, and what gets taken off it (Step 9).
 *
 * THE ONE THING THAT MUST NOT BE GOT WRONG HERE IS PAYING SOMETHING TWICE.
 *
 * A deduction is a row that says "หักเงินอ่อง 200 บาท". It has to come off
 * exactly one payslip, ever. The way that is guaranteed is not by dating it
 * carefully — it is by STAMPING it with the payroll line that consumed it, and
 * only at the moment the payroll is actually paid:
 *
 *  - while a payroll is a DRAFT it consumes nothing. Deductions are gathered
 *    fresh every time the screen is opened, so a lateness recorded five minutes
 *    ago shows up without anyone pressing recalculate.
 *  - the moment it is PAID, every deduction it used is stamped and every figure
 *    on it is frozen. The payslip in someone's hand and the row in the database
 *    now say the same thing forever, whatever is edited afterwards.
 *
 * That is also why the wage terms are snapshotted onto the line (rule #7, the
 * same rule that keeps a menu price change off an open bill): giving someone a
 * raise in August must not quietly rewrite the slip they were handed in July.
 *
 * The second thing that must not be got wrong is counting wages twice in the
 * P&L. Wages reach it as ONE Expense row in the ค่าแรง category, created by
 * paying a payroll and flagged `isAutoGenerated` so Step 8's screens refuse to
 * let anyone hand-edit it. If wages are also typed in by hand as an expense,
 * the month is wrong by a full payroll — so the pay screen looks for that and
 * says so before the button is pressed.
 */

import { z } from 'zod';
import { emailSchema, passwordSchema } from './auth.js';
import { assertBusinessDate, type BusinessDate } from './business-date.js';
import { assertSatang, type Satang } from './money.js';
import { Role, StaffStatus, WageType } from './enums.js';
import {
  businessDateSchema,
  nationalitySchema,
  nonNegativeSatangSchema,
  paidBySchema,
  pinSchema,
  roleSchema,
  staffStatusSchema,
  uuidSchema,
  wageTypeSchema,
  yearMonthSchema,
} from './schemas.js';

/* ------------------------------------------------------------------ */
/* what a wage is worth                                                */
/* ------------------------------------------------------------------ */

/**
 * Gross pay for one person for one month.
 *
 * The two wage types are genuinely different shapes, not one with a divisor:
 *
 *  - DAILY is `rate × days`. Days worked is the whole calculation, and a day
 *    not worked is simply a day not counted.
 *  - MONTHLY is the rate, flat. Days worked is recorded on the slip because it
 *    is worth knowing, but it does NOT scale the money — a salaried cook who
 *    took two days off is not paid 29/31 of a salary, they are paid a salary
 *    minus whatever the shop decided to deduct, and that decision belongs in a
 *    deduction row where it is visible and can be argued with.
 *
 * Pro-rating a monthly salary silently would be the same mistake as any other
 * invisible calculation: nobody could tell it from an error.
 */
export function grossSatangFor(
  wageType: WageType,
  wageRateSatang: Satang,
  daysWorked: number,
): Satang {
  assertSatang(wageRateSatang, 'wage rate');
  if (!Number.isInteger(daysWorked) || daysWorked < 0) {
    throw new RangeError(`daysWorked must be a non-negative integer, got ${daysWorked}`);
  }
  if (wageType === WageType.MONTHLY) return wageRateSatang;
  return wageRateSatang * daysWorked;
}

/**
 * What actually goes in the envelope.
 *
 * Returns the raw arithmetic, negative included. Clamping to zero here would
 * turn "we are taking off more than they earned" — which is a conversation
 * someone has to have — into a payslip reading 0.00 with no explanation.
 */
export function netSatangFor(
  grossSatang: Satang,
  bonusSatang: Satang,
  deductSatang: Satang,
): Satang {
  assertSatang(grossSatang, 'gross');
  assertSatang(bonusSatang, 'bonus');
  assertSatang(deductSatang, 'deduction');
  return grossSatang + bonusSatang - deductSatang;
}

/**
 * true when the deductions swallow the whole wage.
 *
 * The payroll refuses to be paid in this state. There is no carry-forward
 * table in this Step, so the alternative would be either a negative payslip or
 * a balance quietly written off — and the honest fix (shrink the deduction and
 * record the rest next month) is one the owner has to make deliberately.
 */
export function deductionExceedsPay(
  grossSatang: Satang,
  bonusSatang: Satang,
  deductSatang: Satang,
): boolean {
  return netSatangFor(grossSatang, bonusSatang, deductSatang) < 0;
}

/* ------------------------------------------------------------------ */
/* why money was taken off                                             */
/* ------------------------------------------------------------------ */

/**
 * Deduction reasons.
 *
 * A fixed list stored as KEYS, for the same reason expense categories are
 * (Step 8): "มาสาย", "สาย" and "เข้างานสาย" typed as free text are three things
 * that nothing can add together when someone asks how much lateness cost this
 * month.
 */
export const DeductionType = {
  LATE: 'LATE',
  ABSENT: 'ABSENT',
  ADVANCE: 'ADVANCE',
  DAMAGE: 'DAMAGE',
  OTHER: 'OTHER',
} as const;
export type DeductionType = (typeof DeductionType)[keyof typeof DeductionType];

export interface DeductionTypeInfo {
  key: DeductionType;
  label: string;
  hint: string;
}

export const DEDUCTION_TYPES: readonly DeductionTypeInfo[] = [
  { key: DeductionType.LATE, label: 'มาสาย', hint: 'เข้างานช้ากว่าเวลา' },
  { key: DeductionType.ABSENT, label: 'ขาดงาน', hint: 'ไม่มาและไม่ได้ลา' },
  { key: DeductionType.ADVANCE, label: 'เบิกล่วงหน้า', hint: 'ขอเงินไปก่อนวันจ่าย' },
  { key: DeductionType.DAMAGE, label: 'ทำของเสียหาย', hint: 'ชาม แก้ว ของในร้าน' },
  { key: DeductionType.OTHER, label: 'อื่น ๆ', hint: 'ที่ไม่เข้าพวกข้างบน' },
];

const DEDUCTION_BY_KEY = new Map(DEDUCTION_TYPES.map((info) => [info.key as string, info]));

export const deductionTypeSchema = z.nativeEnum(DeductionType);

/** Unrecognised values render as themselves — an old row must not go blank. */
export function deductionTypeLabel(value: string): string {
  return DEDUCTION_BY_KEY.get(value)?.label ?? value;
}

/* ------------------------------------------------------------------ */
/* labels                                                              */
/* ------------------------------------------------------------------ */

export const ROLE_LABEL: Readonly<Record<Role, string>> = {
  [Role.OWNER]: 'เจ้าของร้าน',
  [Role.MANAGER]: 'ผู้จัดการ',
  [Role.STAFF]: 'พนักงาน',
};

export const STAFF_STATUS_LABEL: Readonly<Record<StaffStatus, string>> = {
  [StaffStatus.ACTIVE]: 'ทำงานอยู่',
  [StaffStatus.PROBATION]: 'ทดลองงาน',
  [StaffStatus.LEAVE]: 'ลาพัก',
  [StaffStatus.LEFT]: 'ลาออกแล้ว',
};

export const WAGE_TYPE_LABEL: Readonly<Record<WageType, string>> = {
  [WageType.DAILY]: 'รายวัน',
  [WageType.MONTHLY]: 'รายเดือน',
};

/**
 * Whether somebody belongs on a given month's payroll run.
 *
 * DECIDED BY DATES, NOT BY STATUS, and that distinction is the whole point.
 * The obvious rule — "everyone whose status is not ลาออกแล้ว" — quietly
 * underpays a real person: mark someone as having left on 20 August and
 * August's run drops them, along with the twenty days they actually worked.
 * The owner is looking at a total, not at a headcount, so nothing on the screen
 * says a name is missing.
 *
 * So:
 *  - hired after the month ended  → not on it (a new cook does not get paid for
 *    the month before they arrived).
 *  - left before the month began  → not on it.
 *  - left DURING the month        → on it, and their days settle up.
 *
 * Status is only consulted when there is no leaving date to reason with, which
 * is the one case where it is the sole piece of information available.
 */
export function isOnPayrollForMonth(
  person: {
    status: StaffStatus;
    startDate: BusinessDate;
    endDate?: BusinessDate | null;
  },
  yearMonth: string,
): boolean {
  const [start, endExclusive] = payrollMonthBounds(yearMonth);
  // YYYY-MM-DD compares lexicographically in date order, so no parsing.
  if (person.startDate >= endExclusive) return false;
  if (person.endDate) return person.endDate >= start;
  return person.status !== StaffStatus.LEFT;
}

/** `[first day, first day of next month)` — kept here so this file has no cycle. */
function payrollMonthBounds(yearMonth: string): [BusinessDate, BusinessDate] {
  const [year, month] = yearMonth.split('-').map(Number) as [number, number];
  const next = month === 12 ? `${year + 1}-01` : `${year}-${String(month + 1).padStart(2, '0')}`;
  return [`${yearMonth}-01`, `${next}-01`];
}

/* ------------------------------------------------------------------ */
/* work permits and passports                                          */
/* ------------------------------------------------------------------ */

/**
 * How far ahead a document expiry is worth shouting about.
 *
 * 90 days because renewing a Thai work permit is not a same-week errand, and
 * the shop employing someone whose permit lapsed is the shop's problem, not
 * the employee's. The warning is the entire reason those columns exist.
 */
export const DOCUMENT_WARNING_DAYS = 90;

export type DocumentExpiryState = 'NONE' | 'OK' | 'EXPIRING' | 'EXPIRED';

/** Whole days from one business date to another. Negative = already past. */
export function daysBetween(from: BusinessDate, to: BusinessDate): number {
  assertBusinessDate(from);
  assertBusinessDate(to);
  const MS_PER_DAY = 24 * 60 * 60 * 1000;
  return Math.round((Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / MS_PER_DAY);
}

/**
 * `EXPIRED` on the day it expires, not the day after.
 *
 * A permit valid "ถึง 15 มีนาคม" is one whose last usable day is the 15th, so
 * treating the 15th itself as still fine is a day of illegal employment. Erring
 * one day early costs nothing; erring one day late is the whole risk.
 */
export function documentExpiryState(
  expiry: BusinessDate | null | undefined,
  today: BusinessDate,
): DocumentExpiryState {
  if (!expiry) return 'NONE';
  const days = daysBetween(today, expiry);
  if (days <= 0) return 'EXPIRED';
  if (days <= DOCUMENT_WARNING_DAYS) return 'EXPIRING';
  return 'OK';
}

/* ------------------------------------------------------------------ */
/* staff records                                                       */
/* ------------------------------------------------------------------ */

const nameSchema = z.string().trim().min(1, 'ต้องใส่ชื่อ').max(80, 'ชื่อยาวเกินไป');
const optionalText = (max: number) => z.string().trim().max(max).nullish();

/**
 * A staff member as typed into the management screen.
 *
 * `pin` is separate (see below) and never part of this object — it must not be
 * able to ride along in an update payload that a screen built for editing a
 * phone number, and it must never be echoed back in a response.
 */
const staffFields = z.object({
  fullName: nameSchema,
  nickname: optionalText(40),
  position: optionalText(40),
  role: roleSchema,
  phone: optionalText(20),
  /**
   * Optional and nullable: most people have none, and clearing it is how an
   * account stops being able to reach the back office by username.
   */
  email: emailSchema.nullable().optional(),

  startDate: businessDateSchema,
  endDate: businessDateSchema.nullish(),
  status: staffStatusSchema,

  nationality: nationalitySchema,
  passportNo: optionalText(30),
  passportExpiry: businessDateSchema.nullish(),
  workPermitNo: optionalText(30),
  workPermitExpiry: businessDateSchema.nullish(),

  wageType: wageTypeSchema,
  wageRateSatang: nonNegativeSatangSchema,

  note: optionalText(200),
});

/** Somebody cannot have left before they started. */
const endsAfterStart = {
  check: (value: { startDate: string; endDate?: string | null }) =>
    !value.endDate || value.endDate >= value.startDate,
  options: { message: 'วันที่ออกต้องไม่มาก่อนวันเริ่มงาน', path: ['endDate'] as const },
};

export const staffRequestSchema = staffFields.refine(endsAfterStart.check, {
  ...endsAfterStart.options,
  path: [...endsAfterStart.options.path],
});
export type StaffRequest = z.infer<typeof staffRequestSchema>;

/** Creating someone needs a PIN; editing them leaves the existing one alone. */
export const staffCreateRequestSchema = staffFields
  .extend({ pin: pinSchema })
  .refine(endsAfterStart.check, {
    ...endsAfterStart.options,
    path: [...endsAfterStart.options.path],
  });
export type StaffCreateRequest = z.infer<typeof staffCreateRequestSchema>;

export const staffPinRequestSchema = z.object({ pin: pinSchema });
export type StaffPinRequest = z.infer<typeof staffPinRequestSchema>;

export const staffPasswordRequestSchema = z.object({ password: passwordSchema });
export type StaffPasswordRequest = z.infer<typeof staffPasswordRequestSchema>;

/**
 * A staff member as sent to the screen.
 *
 * Note what is NOT here: pinHash, failedPinAttempts, pinLockedUntil. The hash
 * has no business leaving the server even for an owner — it is the one field
 * that is worth stealing, and a screen that never receives it cannot leak it
 * through a screenshot, a log or a service worker cache.
 */
export const staffDtoSchema = z.object({
  id: uuidSchema,
  fullName: z.string(),
  nickname: z.string().nullable(),
  position: z.string().nullable(),
  role: roleSchema,
  phone: z.string().nullable(),
  /** The back office username. null for everyone who does not have one. */
  email: z.string().nullable(),
  /** Whether a password is set. The hash itself never leaves the API. */
  hasOfficeAccess: z.boolean(),
  /** True while the password lockout is in force, so the screen can say so. */
  isLoginLocked: z.boolean(),

  startDate: businessDateSchema,
  endDate: businessDateSchema.nullable(),
  status: staffStatusSchema,

  nationality: nationalitySchema,
  passportNo: z.string().nullable(),
  passportExpiry: businessDateSchema.nullable(),
  workPermitNo: z.string().nullable(),
  workPermitExpiry: businessDateSchema.nullable(),

  wageType: wageTypeSchema,
  wageRateSatang: nonNegativeSatangSchema,

  note: z.string().nullable(),
  lastLoginAt: z.string().nullable(),
  /** true while the PIN lockout is in force, so the screen can offer a reset. */
  isPinLocked: z.boolean(),
  /**
   * Whether anything in the system points at this person yet. false means the
   * row can still be deleted outright; true means "ลาออก" is the only exit.
   */
  hasHistory: z.boolean(),
});
export type StaffDto = z.infer<typeof staffDtoSchema>;

export const staffListResponseSchema = z.object({
  /** The business date the expiry states below were computed against. */
  today: businessDateSchema,
  staff: z.array(staffDtoSchema),
});
export type StaffListResponse = z.infer<typeof staffListResponseSchema>;

/* ------------------------------------------------------------------ */
/* deductions                                                          */
/* ------------------------------------------------------------------ */

export const deductionRequestSchema = z.object({
  staffId: uuidSchema,
  date: businessDateSchema,
  type: deductionTypeSchema,
  amountSatang: nonNegativeSatangSchema.min(1, 'จำนวนเงินต้องมากกว่า 0'),
  note: optionalText(200),
});
export type DeductionRequest = z.infer<typeof deductionRequestSchema>;

export const deductionDtoSchema = z.object({
  id: uuidSchema,
  staffId: uuidSchema,
  staffName: z.string(),
  date: businessDateSchema,
  type: z.string(),
  amountSatang: nonNegativeSatangSchema,
  note: z.string().nullable(),
  /**
   * Set once a paid payroll has consumed it. Such a row is frozen: editing it
   * would move money that has already been handed over and printed on a slip.
   */
  isSettled: z.boolean(),
});
export type DeductionDto = z.infer<typeof deductionDtoSchema>;

export const deductionListResponseSchema = z.object({
  yearMonth: yearMonthSchema,
  deductions: z.array(deductionDtoSchema),
  totalSatang: nonNegativeSatangSchema,
  /** Not yet on any paid payslip — the amount the next run will pick up. */
  unsettledSatang: nonNegativeSatangSchema,
});
export type DeductionListResponse = z.infer<typeof deductionListResponseSchema>;

/* ------------------------------------------------------------------ */
/* the payroll run                                                     */
/* ------------------------------------------------------------------ */

export const payrollLineUpdateSchema = z.object({
  daysWorked: z.number().int().min(0, 'จำนวนวันต้องไม่ติดลบ').max(31, 'เดือนหนึ่งมีไม่ถึง 31 วัน'),
  bonusSatang: nonNegativeSatangSchema,
  note: optionalText(200),
});
export type PayrollLineUpdate = z.infer<typeof payrollLineUpdateSchema>;

/**
 * Paying a payroll.
 *
 * `paidDate` is a business date the user picks and defaults to today, NOT the
 * last day of the month being paid for. Step 8's P&L is cash basis: the wages
 * hit the month the money actually left the till, which for a payroll run on
 * the 3rd of August is August. Dating it into July to make it "tidy" would
 * silently move a five-figure sum into a month whose figures may already have
 * been read.
 */
export const payrollPayRequestSchema = z.object({
  paidDate: businessDateSchema,
  paidBy: paidBySchema.default('CASH'),
});
export type PayrollPayRequest = z.infer<typeof payrollPayRequestSchema>;

/** One deduction as itemised on a payslip. */
export const payslipDeductionSchema = z.object({
  date: businessDateSchema,
  type: z.string(),
  amountSatang: nonNegativeSatangSchema,
  note: z.string().nullable(),
});
export type PayslipDeduction = z.infer<typeof payslipDeductionSchema>;

export const payrollLineDtoSchema = z.object({
  id: uuidSchema,
  staffId: uuidSchema,
  fullName: z.string(),
  nickname: z.string().nullable(),
  position: z.string().nullable(),

  /**
   * The wage terms AS THEY WERE when this slip was made (rule #7). A raise in
   * August must not rewrite the July slip that is already in someone's hand.
   */
  wageTypeSnapshot: wageTypeSchema,
  wageRateSnapshot: nonNegativeSatangSchema,

  daysWorked: z.number().int().nonnegative(),
  grossSatang: nonNegativeSatangSchema,
  bonusSatang: nonNegativeSatangSchema,
  deductSatang: nonNegativeSatangSchema,
  /** Can be negative on a draft; a payroll in that state refuses to be paid. */
  netSatang: z.number().int(),

  /** Itemised so a slip never says "หัก 500" with nothing to explain it. */
  deductions: z.array(payslipDeductionSchema),
  note: z.string().nullable(),
});
export type PayrollLineDto = z.infer<typeof payrollLineDtoSchema>;

export const payrollResponseSchema = z.object({
  yearMonth: yearMonthSchema,
  /** null until a payroll has been generated for this month. */
  payroll: z
    .object({
      id: uuidSchema,
      /** null = ยังไม่จ่าย. Set = frozen, and the only state that pays anyone. */
      paidAt: z.string().nullable(),
      totalSatang: nonNegativeSatangSchema,
      /** The auto-created ค่าแรง expense, once paid. */
      expenseId: uuidSchema.nullable(),
      lines: z.array(payrollLineDtoSchema),
    })
    .nullable(),

  /**
   * Wages ALREADY typed into the expense screen by hand for the month the
   * payroll would be paid into. Surfaced, not blocked: it is usually a genuine
   * advance to one person, occasionally the entire payroll entered twice, and
   * only the owner can tell which.
   */
  manualWageSatang: nonNegativeSatangSchema,
  /** Anyone on the payroll whose wage rate is still 0 — an easy thing to miss. */
  staffWithoutWageCount: z.number().int().nonnegative(),
});
export type PayrollResponse = z.infer<typeof payrollResponseSchema>;

export const payrollQuerySchema = z.object({ month: yearMonthSchema });
export const deductionListQuerySchema = z.object({ month: yearMonthSchema });
