/**
 * The customer's phone (Step 7).
 *
 * A sticker on the table carries a URL. The customer scans it, sees the menu,
 * taps a bowl, and sends it. NOTHING they send reaches the kitchen on its own:
 * every line lands on the bill marked `source = QR` with `approvedAt = null`,
 * and a member of staff has to press "อนุมัติ" before a cook ever sees it.
 *
 * THAT APPROVAL STEP IS THE WHOLE SECURITY MODEL, and it is why the rest of
 * this file can stay as simple as it is.
 *
 * The token in the URL is the only credential a customer has, and it is printed
 * on a sticker in a public room — so it must be assumed to leak. A photograph
 * of the sticker therefore buys exactly one thing: the ability to put a request
 * in a queue that a human reads. Not a bill, not a kitchen ticket, not a price.
 * Trying to make the token itself secret (rotating it per sitting) was the
 * original plan and it does not survive contact with a printed sticker; see the
 * note on DiningTable.qrToken in schema.prisma.
 *
 * Two consequences run through everything below:
 *
 *  1. A PENDING LINE IS NOT MONEY. It is excluded from the bill total, from the
 *     printed check and from the receipt, and the bill cannot be paid while one
 *     is outstanding. The shop has not agreed to sell anything yet.
 *  2. NOTHING HERE CARRIES COST. The customer endpoints are unauthenticated, so
 *     a field that is merely "not displayed" is a field that is published.
 */

import { z } from 'zod';
import { OrderLineSource } from './enums.js';
import { modifierIdsSchema } from './modifier.js';
import { menuResponseSchema, orderNoteSchema, qtySchema } from './order.js';
import { moveRequestSchema, satangSchema, uuidSchema } from './schemas.js';

/* ------------------------------------------------------------------ */
/* the one definition of "nobody has agreed to this yet"               */
/* ------------------------------------------------------------------ */

/**
 * Whether a bill line is still a request rather than a sale.
 *
 * ONE function, imported by the API mapper, the totals and the screens, because
 * three copies of this condition would drift and the symptom would be a bill
 * whose lines and whose total disagree about what is on it.
 */
export function isAwaitingApproval(line: {
  source: OrderLineSource;
  approvedAt: Date | string | null;
}): boolean {
  return line.source === OrderLineSource.QR && line.approvedAt === null;
}

/* ------------------------------------------------------------------ */
/* the token on the sticker                                            */
/* ------------------------------------------------------------------ */

/**
 * What a table's QR token looks like.
 *
 * Generated by the API as 12 random bytes in base64url — 96 bits, 16
 * characters. Short on purpose: every character is more dots in the QR, and a
 * denser code is a code that a cheap phone camera fails to read across a table
 * at dinner-light. A UUID's dashes would cost four characters for nothing.
 *
 * The upper bound is generous so a token rotated by some later tool does not
 * have to match today's generator byte for byte.
 */
export const qrTokenSchema = z.string().regex(/^[A-Za-z0-9_-]{16,64}$/, 'รหัส QR ไม่ถูกต้อง');

/**
 * The URL printed on the sticker.
 *
 * Built from the origin the MANAGEMENT SCREEN is running on, not from a server
 * setting: the server knows it is `localhost:3001`, which is exactly the
 * address a customer's phone cannot reach. Whoever is looking at the browser is
 * already at an address that works from inside the shop.
 */
export function qrOrderUrl(origin: string, token: string): string {
  return `${origin.replace(/\/+$/, '')}/t/${token}`;
}

/* ------------------------------------------------------------------ */
/* what the customer sends                                             */
/* ------------------------------------------------------------------ */

/**
 * How much one submission may carry.
 *
 * A table of six ordering at once is maybe ten lines. Twenty is room to spare
 * and still a hard stop on a script pointed at an endpoint that needs no login.
 */
export const MAX_QR_LINES_PER_SUBMIT = 20;

export const qrSubmitLineSchema = z.object({
  /**
   * Generated on the PHONE (rule #6), and the reason a flaky 4G double-tap is
   * harmless: the second submission carries the same ids, and the server keeps
   * the row it already has instead of cooking two bowls.
   */
  id: uuidSchema,
  menuItemId: uuidSchema,
  qty: qtySchema.default(1),
  note: orderNoteSchema,
  /** Omitted means the shop's defaults, exactly as on the till. */
  modifierIds: modifierIdsSchema.optional(),
});

export const qrSubmitRequestSchema = z.object({
  lines: z.array(qrSubmitLineSchema).min(1, 'ยังไม่ได้เลือกอะไรเลย').max(MAX_QR_LINES_PER_SUBMIT),
});
export type QrSubmitRequest = z.infer<typeof qrSubmitRequestSchema>;

/* ------------------------------------------------------------------ */
/* what the customer sees                                              */
/* ------------------------------------------------------------------ */

/**
 * Three states, in the customer's words rather than the system's.
 *
 * `PENDING` is the one that matters: it is the difference between "we have your
 * order" (a lie until a human looks) and "we have asked the staff". A customer
 * who thinks a pending bowl is on its way waits twenty minutes and then
 * complains about the kitchen.
 */
export const qrLineStatusSchema = z.enum(['PENDING', 'CONFIRMED', 'COOKING']);
export type QrLineStatus = z.infer<typeof qrLineStatusSchema>;

export const QR_LINE_STATUS_LABEL: Readonly<Record<QrLineStatus, string>> = {
  PENDING: 'รอพนักงานยืนยัน',
  CONFIRMED: 'ยืนยันแล้ว',
  COOKING: 'ส่งครัวแล้ว',
};

export const qrBillLineDtoSchema = z.object({
  id: uuidSchema,
  name: z.string(),
  qty: z.number().int(),
  /** Already joined into "เส้นเล็ก · น้ำใส" — the phone does no work. */
  optionsSummary: z.string().nullable(),
  note: z.string().nullable(),
  lineTotalSatang: satangSchema,
  status: qrLineStatusSchema,
});
export type QrBillLineDto = z.infer<typeof qrBillLineDtoSchema>;

export const qrBillDtoSchema = z.object({
  /** Null until the first submission — an empty table has no bill yet. */
  orderId: uuidSchema.nullable(),
  orderNo: z.string().nullable(),
  lines: z.array(qrBillLineDtoSchema),
  /**
   * CONFIRMED and COOKING lines only.
   *
   * Showing a pending bowl inside the total would tell the customer they owe
   * money for something the shop has not agreed to sell them, and would be the
   * number they argue about at the counter when it is refused.
   */
  confirmedTotalSatang: satangSchema,
  pendingCount: z.number().int().nonnegative(),
});
export type QrBillDto = z.infer<typeof qrBillDtoSchema>;

export const qrTableResponseSchema = z.object({
  shopName: z.string(),
  tableName: z.string(),
  /** False when the shop has switched QR ordering off — the menu still shows. */
  orderingEnabled: z.boolean(),
  /** The same payload the till gets, minus cost: it is never included here. */
  menu: menuResponseSchema,
  bill: qrBillDtoSchema,
});
export type QrTableResponse = z.infer<typeof qrTableResponseSchema>;

export const qrSubmitResponseSchema = z.object({
  bill: qrBillDtoSchema,
  /** How many of the submitted lines were new — a resend reports 0. */
  accepted: z.number().int().nonnegative(),
});
export type QrSubmitResponse = z.infer<typeof qrSubmitResponseSchema>;

/* ------------------------------------------------------------------ */
/* what the staff sees                                                 */
/* ------------------------------------------------------------------ */

/**
 * How long a customer has been waiting for someone to press the button.
 *
 * A pending line is a person sitting at a table looking at their phone, so the
 * clock here is far tighter than the kitchen's. One minute is "nobody has
 * looked yet"; three is long enough that the customer has decided the QR does
 * not work and is waving at a member of staff — which is the entire thing this
 * feature was supposed to prevent.
 */
export const QR_WAIT_WARN_SECONDS = 60;
export const QR_WAIT_LATE_SECONDS = 180;

export type QrWaitUrgency = 'fresh' | 'warn' | 'late';

export function secondsWaiting(submittedAt: Date | string, now: Date = new Date()): number {
  const at = submittedAt instanceof Date ? submittedAt : new Date(submittedAt);
  return Math.max(0, Math.floor((now.getTime() - at.getTime()) / 1000));
}

export function qrWaitUrgency(submittedAt: Date | string, now: Date = new Date()): QrWaitUrgency {
  const seconds = secondsWaiting(submittedAt, now);
  if (seconds >= QR_WAIT_LATE_SECONDS) return 'late';
  if (seconds >= QR_WAIT_WARN_SECONDS) return 'warn';
  return 'fresh';
}

export const pendingApprovalLineDtoSchema = z.object({
  id: uuidSchema,
  name: z.string(),
  qty: z.number().int(),
  optionsSummary: z.string().nullable(),
  note: z.string().nullable(),
  lineTotalSatang: satangSchema,
  submittedAt: z.string(),
});
export type PendingApprovalLineDto = z.infer<typeof pendingApprovalLineDtoSchema>;

export const pendingApprovalOrderDtoSchema = z.object({
  orderId: uuidSchema,
  orderNo: z.string().nullable(),
  tableId: uuidSchema.nullable(),
  tableName: z.string().nullable(),
  lines: z.array(pendingApprovalLineDtoSchema),
  /** The oldest line's timestamp — what the queue sorts and colours by. */
  waitingSince: z.string(),
});
export type PendingApprovalOrderDto = z.infer<typeof pendingApprovalOrderDtoSchema>;

export const pendingApprovalResponseSchema = z.object({
  orders: z.array(pendingApprovalOrderDtoSchema),
});
export type PendingApprovalResponse = z.infer<typeof pendingApprovalResponseSchema>;

export const approveQrLinesRequestSchema = z.object({
  lineIds: z.array(uuidSchema).min(1).max(MAX_QR_LINES_PER_SUBMIT),
  /**
   * Approving and sending to the kitchen are ONE action at the counter.
   *
   * Step 5 keeps them apart for staff orders because the ten seconds after
   * "ก๋วยเตี๋ยวหมู" are when the customer says "อ๋อ ไม่ผักด้วย". A QR order has
   * already been through that: the customer typed it themselves and pressed
   * send. A second button here would only be a way to forget.
   */
  fire: z.boolean().default(true),
});
export type ApproveQrLinesRequest = z.infer<typeof approveQrLinesRequestSchema>;

export const rejectQrLinesRequestSchema = z.object({
  lineIds: z.array(uuidSchema).min(1).max(MAX_QR_LINES_PER_SUBMIT),
  /**
   * Optional and free text, unlike a void reason.
   *
   * A void is money the shop lost and has to be groupable at month end. A
   * rejected QR line is food that was never cooked; the only reader is whoever
   * later asks "is this QR code generating junk", and the audit log answers
   * that by counting rows.
   */
  reason: z.string().max(200).nullish(),
});
export type RejectQrLinesRequest = z.infer<typeof rejectQrLinesRequestSchema>;

/* ------------------------------------------------------------------ */
/* managing the stickers                                               */
/* ------------------------------------------------------------------ */

export const tableQrDtoSchema = z.object({
  id: uuidSchema,
  name: z.string(),
  zone: z.string().nullable(),
  seats: z.number().int(),
  sortOrder: z.number().int(),
  isActive: z.boolean(),
  qrToken: qrTokenSchema,

  /**
   * true once any bill has ever sat on this table.
   *
   * The screen uses it to offer "ปิดใช้" instead of "ลบ", and the API refuses
   * the delete anyway. Deleting would blank the table name off every past bill
   * (`Order.tableId` is an optional relation, so the database quietly sets it
   * null) and cascade away the sittings that tie several bills into one visit.
   * Same rule, same reason, as deleting a member of staff.
   */
  hasHistory: z.boolean(),
  /** true while a bill is open on it — retiring or deleting is refused. */
  hasOpenBill: z.boolean(),
});
export type TableQrDto = z.infer<typeof tableQrDtoSchema>;

export const tableQrResponseSchema = z.object({
  /** The branch-wide switch, so the screen can show what state it is in. */
  orderingEnabled: z.boolean(),
  tables: z.array(tableQrDtoSchema),
});
export type TableQrResponse = z.infer<typeof tableQrResponseSchema>;

export const qrOrderingRequestSchema = z.object({ enabled: z.boolean() });
export type QrOrderingRequest = z.infer<typeof qrOrderingRequestSchema>;

/* ------------------------------------------------------------------ */
/* editing the floor plan                                              */
/* ------------------------------------------------------------------ */

/**
 * A table as the layout editor writes it.
 *
 * `qrToken` is NOT here and never will be: the sticker is a printed credential
 * the server issues, and a rename must not change it — otherwise correcting
 * "A1" to "A01" would send somebody round the room peeling stickers off the
 * furniture. Rotating a token is its own deliberate button.
 *
 * `sortOrder` is not here either. It is decided by the ขึ้น/ลง buttons, which
 * renumber a whole zone server-side; letting the form post a number invites
 * two tables with the same one and an order that then depends on the name.
 */
export const tableRequestSchema = z.object({
  name: z.string().trim().min(1, 'ต้องมีชื่อโต๊ะ').max(20, 'ชื่อโต๊ะยาวเกินไป'),
  /**
   * Free text, and NULLABLE. A shop with one room should not be forced to
   * invent a zone name, and the floor plan already handles the null group.
   */
  zone: z
    .string()
    .trim()
    .max(40)
    .nullish()
    .transform((value) => (value ? value : null)),
  /** Only used to label the table on the floor plan. 0 is legal — a counter seat. */
  seats: z.number().int().min(0, 'จำนวนที่นั่งติดลบไม่ได้').max(50, 'ที่นั่งเยอะผิดปกติ'),
  isActive: z.boolean().default(true),
});
export type TableRequest = z.infer<typeof tableRequestSchema>;

/** The same one-step nudge the menu screen uses — see moveRequestSchema. */
export const tableMoveRequestSchema = moveRequestSchema;
export type TableMoveRequest = z.infer<typeof tableMoveRequestSchema>;

/** The zone a table with no zone is shown under. Display only — stored as null. */
export const NO_ZONE_LABEL = 'ไม่ระบุโซน';

/**
 * Groups tables for the editor and the floor plan, in the order they are shown.
 *
 * Zones come out in the order they are FIRST SEEN in the sorted list, which —
 * because the server sorts by zone then sortOrder — is alphabetical by zone.
 * Doing it here rather than in each screen is what keeps the editor's order
 * and the floor plan's order the same thing; two sorts that drift apart would
 * mean the ขึ้น/ลง buttons move a table somewhere it does not visibly move.
 */
export function groupTablesByZone<T extends { zone: string | null }>(
  tables: readonly T[],
): { zone: string; tables: T[] }[] {
  const groups = new Map<string, T[]>();
  for (const table of tables) {
    const key = table.zone ?? NO_ZONE_LABEL;
    const bucket = groups.get(key);
    if (bucket) bucket.push(table);
    else groups.set(key, [table]);
  }
  return [...groups].map(([zone, rows]) => ({ zone, tables: rows }));
}
